### ISSUE TITLE
回路設計・基板設計

### ISSUE THREAD

**Issue by fujiy** [wasa-rockoon/TERES#1]
回路設計（配線）

- [x] communication
- [x] gnss
- [x] sensor

基板設計

- [x] communication
- [x] gnss
- [x] logger
- [x] sensor

**Comment by fujiy** [comment]
@KeisukeSuganuma 
LoRaモジュールとの通信はI2CじゃなくてUARTかな

**Comment by KeisukeSuganuma** [comment]
すみません、データシートの読み込みが甘かったです。修正後、GNSSの不足分を足したものと同時にコミットします。
